-- BranV demo users (1 admin + 10 members). Password for all: Password123!
-- Idempotent via ON CONFLICT (email/userId).
BEGIN;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_00', 'admin@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'ADMIN', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_00', 'user_seed_00', 'Aarav', 'Mehta', '+91 90000 10001', '1990-04-12'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7000', 'Platinum', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_01', 'rohan.sharma@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_01', 'user_seed_01', 'Rohan', 'Sharma', '+91 90000 10002', '1995-08-23'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7001', 'Gold', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_02', 'priya.nair@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_02', 'user_seed_02', 'Priya', 'Nair', '+91 90000 10003', '1998-01-05'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7002', 'Silver', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_03', 'karan.verma@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_03', 'user_seed_03', 'Karan', 'Verma', '+91 90000 10004', '1992-11-19'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7003', 'Gold', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_04', 'ananya.iyer@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_04', 'user_seed_04', 'Ananya', 'Iyer', '+91 90000 10005', '1996-06-30'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7004', 'Platinum', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_05', 'vikram.singh@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_05', 'user_seed_05', 'Vikram', 'Singh', '+91 90000 10006', '1989-03-14'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7005', 'Silver', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_06', 'neha.gupta@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_06', 'user_seed_06', 'Neha', 'Gupta', '+91 90000 10007', '2000-09-09'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7006', 'Bronze', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_07', 'arjun.reddy@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_07', 'user_seed_07', 'Arjun', 'Reddy', '+91 90000 10008', '1994-12-01'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7007', 'Gold', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_08', 'sneha.das@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', NULL, 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_08', 'user_seed_08', 'Sneha', 'Das', '+91 90000 10009', '1997-07-18'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7008', 'Silver', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_09', 'rahul.jain@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'ACTIVE', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_09', 'user_seed_09', 'Rahul', 'Jain', '+91 90000 10010', '1993-02-27'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7009', 'Bronze', now(), now()) ON CONFLICT ("userId") DO NOTHING;
INSERT INTO users (id, email, "passwordHash", role, status, "emailVerifiedAt", "failedLoginCount", "createdAt", "updatedAt") VALUES ('user_seed_10', 'meera.pillai@branv.test', '$argon2id$v=19$m=19456,t=2,p=1$/klmcSE0SYmJBQxI2ALNrg$WQNwwvWlJ2haZdvfjpC2sSGHkc8T9izt/86VkLMkto4', 'MEMBER', 'SUSPENDED', now(), 0, now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO member_profiles (id, "userId", "firstName", "lastName", phone, dob, "avatarUrl", tier, "createdAt", "updatedAt") VALUES ('mprofile_seed_10', 'user_seed_10', 'Meera', 'Pillai', '+91 90000 10011', '1991-10-08'::timestamp, 'https://loremflickr.com/400/400/portrait,face?lock=7010', 'Silver', now(), now()) ON CONFLICT ("userId") DO NOTHING;
COMMIT;