"""
Slug utility - port of `apps/api/src/common/utils/slug.ts`.

Output MUST match the TypeScript implementation byte-for-byte so URLs
generated by either backend collide deterministically (e.g. brand slugs
written by the FastAPI port still match the Nest-generated routes).
"""

from __future__ import annotations

import re
import unicodedata
from typing import Awaitable, Callable


def slugify(text: str) -> str:
    """
    "Tommy Hilfiger"        → "tommy-hilfiger"
    "Levi's 501® Original"  → "levis-501-original"
    """
    # NFKD normalization + strip combining marks (diacritics).
    normalized = unicodedata.normalize("NFKD", text)
    stripped = "".join(c for c in normalized if not unicodedata.combining(c))
    s = stripped.lower().strip()
    # Same regex steps as the TypeScript version, in order.
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-+", "-", s)
    s = s.strip("-")
    return s


async def ensure_unique_slug(
    base: str,
    is_taken: Callable[[str], Awaitable[bool]],
) -> str:
    """Append -2, -3, ... until is_taken returns False."""
    candidate = base
    i = 1
    while await is_taken(candidate):
        i += 1
        candidate = f"{base}-{i}"
    return candidate
