"""
Audit service - port of `apps/api/src/audit/audit.service.ts`.

Behavior parity:
  * `record(...)` MUST NOT raise - audit failures must not block the caller.
    The Nest impl swallows in a try/catch and logs the error. We do the same.
  * Wire into auth flows as a fire-and-forget `BackgroundTasks.add_task(...)`
    so the audit write happens after the response has been sent.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import and_, distinct, func, insert, select
from sqlalchemy.ext.asyncio import AsyncSession

from ..core.logging import get_logger
from ..core.pagination import make_page
from ..db.models import AuditLog, User
from ..db.session import get_engine

log = get_logger("audit")


@dataclass(slots=True)
class AuditListQuery:
    page: int = 1
    pageSize: int = 50
    actorId: str | None = None
    action: str | None = None
    targetType: str | None = None
    from_: datetime | None = None
    to: datetime | None = None


async def record(
    *,
    action: str,
    actorId: str | None = None,
    targetType: str | None = None,
    targetId: str | None = None,
    ip: str | None = None,
    userAgent: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> None:
    """Single best-effort audit write. Swallows all exceptions."""
    try:
        engine = get_engine()
        async with engine.begin() as conn:
            # cuid is generated by the DB? - Prisma generates via @default(cuid())
            # which is JS-side. We mint one here so we don't depend on a DB
            # trigger that doesn't exist.
            import secrets, string  # noqa: PLC0415  (lazy import - module load cost)
            alphabet = string.ascii_lowercase + string.digits
            new_id = "c" + "".join(secrets.choice(alphabet) for _ in range(24))
            await conn.execute(
                insert(AuditLog).values(
                    id=new_id,
                    actorId=actorId,
                    action=action,
                    targetType=targetType,
                    targetId=targetId,
                    ip=ip,
                    userAgent=userAgent,
                    metadata_=metadata,
                    createdAt=datetime.now(timezone.utc).replace(tzinfo=None),
                )
            )
    except Exception as e:  # noqa: BLE001  - explicit; mirrors Nest's catch-all
        log.error("audit_write_failed", action=action, error=str(e))


async def list_audit_logs(db: AsyncSession, q: AuditListQuery) -> dict[str, Any]:
    """
    Admin list endpoint - returns the same payload Nest does:
      { data, page, pageSize, total, totalPages, actions }
    where `actions` is a distinct list of action strings (populates the UI filter).
    """
    conds = []
    if q.actorId:
        conds.append(AuditLog.actorId == q.actorId)
    if q.action:
        # Case-insensitive substring match (Nest uses Prisma `contains` + `insensitive`).
        conds.append(func.lower(AuditLog.action).contains(q.action.lower()))
    if q.targetType:
        conds.append(AuditLog.targetType == q.targetType)
    if q.from_ is not None:
        conds.append(AuditLog.createdAt >= q.from_)
    if q.to is not None:
        conds.append(AuditLog.createdAt <= q.to)
    where_clause = and_(*conds) if conds else True  # noqa: E712

    total = (await db.execute(
        select(func.count()).select_from(AuditLog).where(where_clause)
    )).scalar_one()

    rows = (await db.execute(
        select(AuditLog, User.id_, User.email, User.role)
        .outerjoin(User, User.id_ == AuditLog.actorId)
        .where(where_clause)
        .order_by(AuditLog.createdAt.desc())
        .offset((q.page - 1) * q.pageSize)
        .limit(q.pageSize)
    )).all()

    distinct_actions = (await db.execute(
        select(distinct(AuditLog.action))
        .order_by(AuditLog.action.asc())
        .limit(100)
    )).scalars().all()

    serialized = [_serialize(row) for row in rows]
    return {
        **make_page(serialized, total, q.page, q.pageSize),
        "actions": distinct_actions,
    }


def _serialize(row) -> dict[str, Any]:
    log, actor_id, actor_email, actor_role = row
    return {
        "id": log.id_,
        "actorId": log.actorId,
        "action": log.action,
        "targetType": log.targetType,
        "targetId": log.targetId,
        "ip": log.ip,
        "userAgent": log.userAgent,
        "metadata": log.metadata_,
        "createdAt": _iso_ms(log.createdAt),
        "actor": (
            {"id": actor_id, "email": actor_email, "role": actor_role}
            if actor_id
            else None
        ),
    }


def _iso_ms(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%S.") + f"{dt.microsecond // 1000:03d}Z"
